### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by YoloSanta** [ThatKawaiiSam/Minutus#1]
Hovering over an item in the GUI then spamming 1 will dupe the item and begin stacking them

**Comment by ThatKawaiiSam** [comment]
Can't seem to replicate this, and as far as I'm aware this would be a client-sided issue. As long as the Menu#shouldCancel method is true - it will prevent items from being taken from the menu. 

Would you be able to put the code that you used?

**Comment by YoloSanta** [comment]
My bad realized the Menu#shouldCancel function was set to false.
